---
title: "aarti_report"
author: "Naomi Liftman"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r warning = FALSE, message = FALSE, error = FALSE}
#loading the necessary libraries 
library(tidyverse)
library(ggplot2)
library(rio)
library(ggthemes)
```

```{r}
#importing the stuff
roster <- import("roster_for_analysis.csv")

#making some changes 
#remove Seattle and change to medicine
roster$College <- sub("Seattle", "Medicine", roster$College)
#removing assistant without tenure to just assistant since asssitant prof
#cannot have tenure! 
roster$Title <- sub("Assistant Professor without Tenure", "Assistant Professor", roster$Title)
#changing Adjunct Assistant Professor to just assistant professor 
#the nuances are not super important in this analysis
roster$Title <- sub("Adjunct Assistant Professor", "Assistant Professor", roster$Title)
#changing Associate Professor without tenure to just Associate professor 
roster$Title <- sub("Associate Professor without tenure", "Associate Professor", roster$Title)
#fixing built environments from Built Envionments
roster$College <- sub("Built Envionments", "Built Environments", roster$College)
#fixing enginneer
roster$College <- sub("Enginnering", "Engineering", roster$College)
#renaming the Evans school
roster$College <- sub("Evans School of Public Policy & Governance", "Evans", roster$College)

#remove the lines with Senior Lecturer and ROTC bc what the heck even are those
roster_cleaned <- roster %>% 
  filter(Title != "ROTC Professor") %>% 
  filter(Title != "Senior Lecturer")
```

```{r}
#grouping by the council
roster_first <- roster %>% 
  group_by(Council) %>% 
  count(Title)
#turns out this is deeply unhelpful
fcas <- roster_first %>% 
  filter(Council == "FCAS")
```

#First graph attempt
```{r}
#realizing I dont need to make graphs for this haha
ggplot(data = fcas, aes(x = Title, y = n)) +
  geom_point()
```

# making hot tables
```{r}
college <- roster %>% 
  group_by(College) %>% 
  count(Title)

#there are 26 total - this makes a graph for each of them, but might be best to do just a few at a time
ggplot(roster, aes(x = Title)) + 
  facet_wrap(~College) +
  geom_bar()

```

```{r}
#selecting specific ones and then making graph
art_astro <- roster %>% 
  filter(College == "Arts & Sciences" | College == "Astronomy")

#have to alphebatize 

#just astro and arts 
ggplot(art_astro, aes(x = Title)) + 
  facet_wrap(~College) +
  geom_bar() +
  coord_flip() +
  theme_bw() 

#medicine
art_astro_med <- roster %>% 
  filter(College == "Arts & Sciences" | College == "Astronomy" | College == "Medicine")

#now medicine toooo
ggplot(art_astro_med, aes(x = Title)) + 
  facet_wrap(~College) +
  geom_bar() +
  coord_flip() +
  theme_igray() +
  scale_y_continuous(breaks = seq(1, 10, by = 1)) 
```

```{r}
#try other things against medicine to see if they are in the same order
#medicine + 
bio_built_med <- roster %>% 
  filter(College == "Biology" | College == "Built Environments" | College == "Medicine")

#now medicine toooo
ggplot(bio_built_med, aes(x = Title)) + 
  facet_wrap(~College) +
  geom_bar() +
  coord_flip() +
  theme_igray() +
  scale_y_continuous(breaks = seq(1, 10, by = 1)) 
```

#Need to include both Medicine and A&S to get all 8 types 
```{r}
#lets try it with count instead! 
roster_count <- roster_cleaned %>% 
  group_by(College) %>% 
  count(Title)

ggplot(roster_count, aes(x = Title, y = n, fill = Title)) + 
  facet_wrap(~College) +
  coord_flip() +
  geom_col() +
  scale_fill_brewer(palette = "RdPu") +
  theme(axis.text.y = element_blank()) +
  scale_y_continuous(breaks = seq(1, 10, by = 1)) 
  
```



