---
title: "top priority item"
author: "Naomi Liftman"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r message = FALSE, warning = FALSE, error = FALSE}
# loading the necessary libraries
library(tidyverse)
library(ggplot2)
library(rio)
library(stringr)
library(RColorBrewer)
library(gt)
library(gtExtras)
library(data.tree)
library(treemap)
```

# Teaching for top priority item 

```{r}
#pulling the data and just getting the qualitative responses 
survey_hopefully <- import("well_being_survey.xlsx") %>% 
  rename( "first_priority" = 17,
          "second_priority" = 18,
          "third_priority" = 19)

teaching_priority <- survey_hopefully %>% 
  select(first_priority:third_priority)
```

# Selecting just the first prirorites 

```{r}
#counting peoples top priorities 
teaching_df <- teaching_priority %>% 
  drop_na(first_priority) %>% 
  count(first_priority) 

#removing the rows that make no sense (are numbers)
teaching_df_clean <- teaching_df[-c(1:11, 21), ]
```

# Graphing it baby
```{r}
ggplot(data = teaching_df_clean, aes(x = first_priority, y = n, fill = first_priority)) + 
  geom_col() +
  theme(axis.text.x = element_text(angle= 45, hjust = 1)) +
  labs(x = "Item", y = "Count", title = "Top Priority in Teaching") + 
  scale_colour_brewer(palette = 1)

```


# Selecting second priorities

```{r}
#counting peoples top priorities 
teaching_df_two <- teaching_priority %>% 
  drop_na(second_priority) %>% 
  count(second_priority) 

#removing the rows that make no sense (are numbers)
teaching_df_clean_two <- teaching_df_two[-c(1:11, 21), ]
```

# Graphing it baby
```{r}
ggplot(data = teaching_df_clean_two, aes(x = second_priority, y = n, fill = second_priority)) + 
  geom_col() +
  theme(axis.text.x = element_text(angle= 45, hjust = 1)) +
  labs(x = "Item", y = "Count", title = "Top Priority in Teaching") + 
  scale_colour_brewer(palette = 1)

```
# Selecting third priorities

```{r}
#counting peoples top priorities 
teaching_df_three <- teaching_priority %>% 
  drop_na(third_priority) %>% 
  count(third_priority) 

#removing the rows that make no sense (there are for some reason a lot on this one)
teaching_df_three_clean <- teaching_df_three %>% 
  filter(n != 1)
```

# Graphing it baby
```{r}
ggplot(data = teaching_df_three_clean, aes(x = third_priority, y = n, fill = third_priority)) + 
  geom_col() +
  theme(axis.text.x = element_text(angle= 45, hjust = 1)) +
  labs(x = "Item", y = "Count", title = "Top Priority in Teaching") + 
  scale_colour_brewer(palette = 1)

```

# Merging the dataframes
```{r}
#renameing the n to the count for the top choice
teaching_df_clean <- teaching_df_clean %>% 
  rename("count_first" = n)

#renaming the n to the count for the second choice
teaching_df_clean_two <- teaching_df_clean_two %>% 
  rename("count_second" = n)

#joining them!!!!
by <- join_by(first_priority == second_priority)
top_two <- full_join(teaching_df_clean, teaching_df_clean_two, by)

#adding our final group horray!!!
teaching_df_three_clean <- teaching_df_three_clean %>% 
  rename("count_third" = n)

by_part_two = join_by(first_priority == third_priority)
top_tree <- full_join(top_two, teaching_df_three_clean, by_part_two)

```


# Creating a data tree based on the dataframes merged
```{r}
ggplot(data = by_part_two)
```





